# Generated by Django 4.0.2 on 2022-03-25 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_exercise_category_alter_exercise_picture'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='like',
            new_name='Favourite',
        ),
    ]
